version: '1.0.{build}'
image:
- Visual Studio 2017
- Visual Studio 2015
configuration:
- Debug
- Release
platform:
- x64
init:
- cmd: |-
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set GENERATOR="Visual Studio 15 2017 Win64" )
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set GENERATOR="Visual Studio 14 2015 Win64" )
    echo %GENERATOR%
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake .. -G %GENERATOR%
build:
  project: build\forensics.sln
  verbosity: minimal
  parallel: true
test_script:
- cmd: |-
    .\%CONFIGURATION%\test_runner.exe
